import matplotlib.pyplot as plt

"""
Set of mock patches to apply for different modules. 

These patches are imported in the test function files in tests/, 
automatically generated by `test_generator.py`.
"""

example1_patch_dict = {
    'module' : 'all_questions_example1',
    'function_name': 'question1',
    'patched_functions': {}
}

example2_add_patch_dict = {
    'module' : 'all_questions_example2',
    'function_name': 'question_add',
    'patched_functions': {}
}

example2_diff_patch_dict = {
    'module' : 'all_questions_example2',
    'function_name': 'question_diff',
    'patched_functions': {}
}
